# Generated by Django 3.2.3 on 2021-12-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(verbose_name='código')),
                ('categoria', models.CharField(choices=[('L', 'Leve'), ('G', 'Grave'), ('M', 'Muy Grave')], default='L', max_length=1, verbose_name='categoría')),
                ('descripcion', models.TextField(verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaDisciplinariaEstudiantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se cometió la falta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('falta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.falta')),
            ],
            options={
                'verbose_name': 'Falta disciplinaria de estudiante',
                'verbose_name_plural': 'Faltas disciplinarias de estudiantes',
            },
        ),
    ]
