# Generated by Django 3.2.10 on 2022-01-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faltadisciplinariaestudiantil',
            options={'verbose_name': 'falta disciplinaria de estudiante', 'verbose_name_plural': 'faltas disciplinarias de estudiantes'},
        ),
    ]
