# Generated by Django 3.2.10 on 2021-12-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_delete_estudiantesymenores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menordeedad',
            name='institucion_educativa',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='familiares',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estudiantes_en_la_misma_casa',
            field=models.ManyToManyField(blank=True, help_text='Ingrese estudiantes que viven en la misma casa.', related_name='_personas_estudiante_estudiantes_en_la_misma_casa_+', to='personas.Estudiante'),
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='MenorDeEdad',
        ),
    ]
