# Generated by Django 3.2.10 on 2022-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('personas', '0004_auto_20211228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='secciones',
            field=models.ManyToManyField(related_name='estudiantes', to='escuela.Seccion'),
        ),
    ]
