# Generated by Django 3.2.10 on 2022-01-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_alter_estudiante_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='seccion2022',
        ),
    ]
