# Generated by Django 3.2.10 on 2022-01-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alter_seccion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveleducativo',
            options={'ordering': ['edad_normal_de_ingreso', 'nivel'], 'verbose_name_plural': 'niveles educativos.'},
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'verbose_name_plural': 'períodos escolares'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nivel_educativo__edad_normal_de_ingreso', 'nivel_educativo', 'seccion'], 'verbose_name': 'sección', 'verbose_name_plural': 'secciones'},
        ),
    ]
