# Generated by Django 3.2.10 on 2022-07-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_auto_20220109_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveleducativo',
            options={'ordering': ['edad_normal_de_ingreso', 'nivel'], 'verbose_name': 'nivel educativo', 'verbose_name_plural': 'niveles educativos'},
        ),
    ]
